package com.study.demo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setFacebookId(java.lang.Long facebookId) {
		set("facebookId", facebookId);
	}
	
	public java.lang.Long getFacebookId() {
		return getLong("facebookId");
	}

	public void setCoins(java.lang.Long coins) {
		set("coins", coins);
	}
	
	public java.lang.Long getCoins() {
		return getLong("coins");
	}

	public void setPass(java.lang.String pass) {
		set("pass", pass);
	}
	
	public java.lang.String getPass() {
		return getStr("pass");
	}

}
